### ISSUE TITLE
Sample is simply not working

### ISSUE THREAD

**Issue by dev-fJ-del** [AvantiPoint/mobileauth-lib#5]
I've configured for google oAuth, added my client id and secret.
Allowed localhost:7127 as well as `https://localhost:7172/signin-google` and `https://localhost:7172/mobileauth/google` on `Authorized redirect URIs`
Simply not working.

**Comment by meron1122** [comment]
Agree.
@dansiegel  Can you provide what set in redirect uri in google? :)

**Comment by dansiegel** [comment]
For instructions on how to configure Google please see the [Microsoft docs](
https://learn.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-6.0&WT.mc_id=DT-MVP-5002924).

Your authorized redirect will be something like `https://<your domain>/signin-google`.

You may want to use https://ngrok.com/ for local development testing. For this you'll need to run your api locally and set it up with ngrok then update the OAuth providers and your app should all use the ngrok domain that it gives you. That way you can test on emulators and real devices since it's not localhost for the device you're testing on.
